import {
    BadgeCheck,
    BarChart3,
    Boxes,
    Briefcase,
    Building2,
    Calculator,
    CalendarCheck,
    CalendarDays,
    Circle,
    ClipboardCheck,
    ClipboardList,
    Clock,
    Coins,
    Contact,
    Database,
    DatabaseZap,
    Download,
    FileBadge,
    HandCoins,
    Inbox,
    Fingerprint,
    House,
    IdCard,
    Landmark,
    Layers,
    LayoutGrid,
    ListTree,
    MapPin,
    Network,
    Package,
    Plug,
    Receipt,
    ScrollText,
    Settings,
    ShoppingCart,
    Shield,
    SlidersHorizontal,
    Stethoscope,
    Table2,
    Tags,
    Warehouse,
    Timer,
    TrendingUp,
    UserCog,
    Users,
    UsersRound,
    Wallet,
    type LucideIcon,
} from 'lucide-react';

/**
 * Allowlist of icons that menus may reference by name. Keeping this explicit
 * avoids bundling the entire lucide set and keeps menu data in sync with the UI.
 */
export const menuIcons: Record<string, LucideIcon> = {
    LayoutGrid,
    Users,
    UserCog,
    Shield,
    ListTree,
    Building2,
    BadgeCheck,
    Database,
    Settings,
    Network,
    Contact,
    DatabaseZap,
    IdCard,
    Briefcase,
    Layers,
    Wallet,
    MapPin,
    UsersRound,
    FileBadge,
    BarChart3,
    Plug,
    Fingerprint,
    ShoppingCart,
    CalendarCheck,
    CalendarDays,
    ClipboardCheck,
    ClipboardList,
    Clock,
    Download,
    HandCoins,
    House,
    Inbox,
    SlidersHorizontal,
    Stethoscope,
    Timer,
    Calculator,
    Landmark,
    Package,
    Boxes,
    Receipt,
    TrendingUp,
    Table2,
    Tags,
    Coins,
    Warehouse,
    ScrollText,
};

export const menuIconNames = Object.keys(menuIcons);

export function iconFromName(name?: string | null): LucideIcon {
    if (name && menuIcons[name]) {
        return menuIcons[name];
    }

    return Circle;
}
